const express = require("express");
const {createUser,loginUserController,getAllUser,getAUser,updateUser,deleteAUser} = require("../controller/userController");
const router= express.Router();
router.post("/signup",createUser);
router.post("/login",loginUserController);
router.get("/all-users",getAllUser);
router.get("/:id",getAUser);
router.put("/:id",updateUser);
router.delete("/:id",deleteAUser);
module.exports = router;